"""adds bcrypt for password hashing

Revision ID: 56fad45fc2ae
Revises: 43934398139c
Create Date: 2024-07-10 21:42:51.940874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56fad45fc2ae'
down_revision = '43934398139c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',  new_column_name='_password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_password',  new_column_name='password')

    # ### end Alembic commands ###
