"""adds image link column to destination table

Revision ID: 5bb64a507ebe
Revises: 56fad45fc2ae
Create Date: 2024-07-15 20:06:29.348753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bb64a507ebe'
down_revision = '56fad45fc2ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('destinations', schema=None) as batch_op:
        batch_op.drop_column('link')

    # ### end Alembic commands ###
